
export const USER_ACTION_TYPES = {
    SET_CURRENT_USER: 'user/SET_CURRENT_USER',
    CHECK_USER_SESSION:'user/CHECK_USER_SESSION',
    GOOGLE_SIGNIN_START:'user/GOOGLE_SIGNIN_START',
    EMAIL_SIGNIN_START:'user/EMAIL_SIGNIN_START',
    SIGNIN_SUCCESS:'user/SIGNIN_SUCCESS',
    SIGNIN_FAILES:'user/SIGNIN_FAILES',
    SIGN_UP_START:'user/SIGN_UP_START',
    SIGN_UP_SUCCESS:'user/SIGN_UP_SUCCESS',
    SIGN_UP_FAILS:'user/SIGN_UP_FAILS',
    SIGN_OUT_START:'user/SIGN_OUT_START',
    SIGN_OUT_SUCCESS:'user/SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILS:'user/SIGN_OUT_FAILS',
  };